# Generated by Django 5.0.1 on 2025-03-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_borrowrequest_student_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
