# Generated by Django 5.0.2 on 2025-04-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='good', max_length=20),
        ),
    ]
