# Generated by Django 5.0.1 on 2025-03-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrequest',
            options={'permissions': [('approve_borrowrequest', 'Can approve borrow requests')]},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'permissions': [('modify_equipment', 'Can modify equipment')]},
        ),
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='Equipment',
            new_name='equipment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
